# Generated by Django 5.0.6 on 2024-06-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_person_address_remove_person_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(default='Unknown address', max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(default='Unknown city', max_length=100),
        ),
    ]
